MELOSYS-4221 - Legger til hittil ubrukte felter fra altinn-søknad
navikt/melosys-schema pull request #207
Opened 2021-01-12 14:02 UTC by JohanSakshaug

Legger til data så test passerer når vi er enige om navn

2021-01-12 14:06 UTC, JohanSakshaug commented on schema/behandlingsgrunnlag-definitions.json
> +          "arbeidUtlandHjemmekontor",
Litt usikker på hvorfor denne har `arbeidUtland` foran, ville bare `hjemmekontor` vært bedre?

2021-01-13 14:56 UTC, JohanSakshaug commented
Ble litt lurt av at `arbeidUtlandHjemmekontor` lå innenfor arrayen her, men det ser da ut på xsd og [skisse](https://www.figma.com/file/7valEmRFMgUIh4MIh7N0SC/Sidemeny?node-id=286%3A6498) som opplysning om hjemmekontor og fast arbeidssted bare skal oppgis en gang, og ikke en gang per arbeidssted 😬

2021-01-13 16:06 UTC, JohanSakshaug commented on schema/behandlingsgrunnlag-definitions.json
> +        "foretak",
(`foretak` pga. `foretakNavn` og `foretakOrgnr`..)

2021-01-25 17:07 UTC, frans-a requested changes
Se https://github.com/navikt/melosys-api/pull/432/files#diff-956c986fbb084d91dc7217e73aa5705669b4a1ec9a90d93001a394b0d27fa365 for hvordan jeg synes fysiske arbeidssteder bør se ut.

Nå det gjelder maritime arbeidssteder er jeg ikke helt sikker på at vi bør ta i bruk `innretningstype`. Jeg tenker på `installasjonstype` siden vi allerede har `installasjonsLandkode` eller `installasjonsLandkode` -> `innretningLandkode`. Ellers kan man tenke på `enhetstype` for både offshore og skip, men det virker litt unødvendig. Hvordan skiller frontend mellom offshore og skip?

Vi bør også tenke å fjerne 
`foretakNavn` og `foretakOrgnr` i `maritimtArbeid` siden det ikke trengs lenger (har stilt spørsmål på Slack #melosys-fag)



Ingen endringer nødvendige for `luftfartBaser`.

2021-01-26 09:31 UTC, JohanSakshaug commented
> Nå det gjelder maritime arbeidssteder er jeg ikke helt sikker på at vi bør ta i bruk innretningstype. Jeg tenker på installasjonstype siden vi allerede har installasjonsLandkode eller installasjonsLandkode -> innretningLandkode.

Jeg brukte `innretningstype` siden det het det i kodeverk, men det gir mening at det burde samsvare med `installasjonsLandKode`. Burde vi la fag bestemme `innretning` eller `installasjon`?

> Hvordan skiller frontend mellom offshore og skip?

Hvis `installasjonsLandkode` er `null` -> skip. Hvis ikke `null` -> offshore

2021-01-26 11:37 UTC, frans-a commented
Det ser ut som fag har valgt innretning i #melosys-fag, så det blir `innretningstype` og `innretningslandkode` eller `innretningLandkode`.

2021-01-26 12:09 UTC, JohanSakshaug commented
Synes det er vanskelig å velge mellom `innretningslandkode` og `innretningLandkode`. 🙂  `innretningLandkode` passer kanskje best med de feltene som allerede er i maritimt arbeid..(?)

2021-01-26 12:40 UTC, frans-a commented
Enig i at det passer best med feltene som finnes.

2021-01-27 09:07 UTC, frans-a approved these changes

2021-01-27 09:51 UTC, JohanSakshaug commented
Vi får koordinere merge av denne når FE og BE er klare.

2021-01-27 13:05 UTC, AStrand94 approved these changes
👌

2021-02-12 18:03 UTC, merged